### ISSUE TITLE
issue in saving file nuclei 

### ISSUE THREAD

**Issue by Ahsan-x** [memN0ps/Reconnaissance#2]
![image](https://user-images.githubusercontent.com/46222314/83341824-626fa480-a301-11ea-8500-f9e70e4310f3.png)
Getting Error on this 
![image](https://user-images.githubusercontent.com/46222314/83341908-00636f00-a302-11ea-96a6-16b6482762d5.png)

**Comment by dwisiswant0** [comment]
Please [open an issue](https://github.com/projectdiscovery/nuclei/issues) on the corresponding repository.

**Comment by Ahsan-x** [comment]
Ok
